### ISSUE TITLE
No information after adding OpenStack provider

### ISSUE THREAD

**Issue by akshaygin** [enhance-manageiq/project-setup#1]
I have installed OpenStack using packstack. Successfully added OpenStack provider in ManageIQ. It shows green check mark as well. But ManageIQ does not show information in 'Relationship' except security groups.

Error:
https://imgur.com/a/NcicX

Excepted Output:
ManageIQ should display OpenStack information such as Flavors, Instances, Images etc.

**Comment by akshaygin** [comment]
Here is the full log of this issue. From file /var/www/miq/vmdb/log/fog.log

[miq_error.log](https://github.com/enhance-manageiq/project-setup/files/1504070/miq_error.log)

**Comment by son-vyas** [comment]
**Openstack-pike** version is not supported by fog/openstack  i.e  v2 is supported and v2.1 is not supported I guess.
[talk.manageiq-forum](http://talk.manageiq.org/t/cannot-see-information-after-adding-openstack-provider/2880/5)

**Comment by son-vyas** [comment]
We need to go for ceilometer configuration

**Comment by akshaygin** [comment]
As OpenStack-pike is latest release it has compatibility issue. Use ocata or Newton for now
