### ISSUE TITLE
Script Error while requesting for service

### ISSUE THREAD

**Issue by akshaygin** [enhance-manageiq/project-setup#4]
We have added Service Dialogue from [here](https://github.com/psachin/openstack-ansible-inside/blob/create_instance/dialogues/dialog_OpenStack%20%7C%20Create%20External%20Network.yml) to create a service for OpenStack external network. But at a time of ordering that service, options(OpenStack Host, Openstack User) from dialogue are showing *<Script error>* 

![screenshot from 2018-01-30 14-34-12](https://user-images.githubusercontent.com/16691314/35575183-acb2fe84-05d3-11e8-8209-402a712c78dd.png)

Probably this is because of error/mistake in yaml or ruby files in the repo. 

Expected Output:
Dialogue should enlist openstack hosts available.

**Comment by KhushbuB** [comment]
The error was solved successfully by adding a custom domain in data store and prioritising it to the top. We were able to see the list of openstack hosts available.
